# -*- coding: utf-8 -*-
"""Task2a.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SSH2U2gMm1BolvzPCXoyeLmLA7yLhSxA
"""

#Name: Md Hasib Ullah Khan Alvie
#Section:23
#Student Id :22101371

input_file = open("input2a.txt", "r")
output_file = open("output2a.txt", "w")

t1 = input_file.readline().strip().split(" ")
arr1 = input_file.readline().strip().split()

t2 = input_file.readline().strip().split(" ")
arr2= input_file.readline().strip().split()

new_arr = []
for i in arr1:
    new_arr.append(int(i))
for j in arr2:
    new_arr.append(int(j))
new_arr.sort()

for i in new_arr:
    output_file.write(f"{i} ")

input_file.close()
output_file.close()