# -*- coding: utf-8 -*-
"""Task1a.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ksUyrFN3Z81rcNM9wNjj5KjkHPsS6_Av
"""

#Name: Md Hasib Ullah Khan Alvie
#Section:23
#Student Id :22101371

input_file = open("input1a.txt", "r")
output_file= open ("output1a", "w")

f = input_file.readline().strip().split(" ")
t = input_file.readline().strip().split(" ")

check = int(f[1])

flag = False

for i in range(0,len(t)-1):
    for j in range(i+1,len(t)):
        if (int(t[i])+int(t[j]))== check:
            output_file.write(f"{i+1} {j+1}")
            flag = True
            break
    if flag == True:
        break

if flag == False:
    output_file.write("IMPOSSIBLE")

input_file.close()
output_file.close()