# -*- coding: utf-8 -*-
"""Task1b.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vKMzoAwyXIHRKxDuoQ66DCRtZk2Wo2SH
"""

#Name: Md Hasib Ullah Khan Alvie
#Section:23
#Student Id :22101371

input_file = open("input1b.txt", "r")
output_file = open("output1b.txt", "w")

f = input_file.readline().strip().split(" ")
t = input_file.readline().strip().split(" ")

n = int(f[0])
check = int(f[1])

i = 0
j = n-1
flag = False

while i!=j:
    if i<j :
        if (int(t[i])+int(t[j])) != check :
            i+=1
        elif (int(t[i])+int(t[j])) == check:
            output_file.write(f"{i+1} {j+1}")
            flag = True
            break
if flag == False:
    output_file.write("IMPOSSIBLE")

input_file.close()
output_file.close()