# -*- coding: utf-8 -*-
"""Task2b.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kDn76hsmj-_ysn1R7RKdi6JATA04z43A
"""

#Name: Md Hasib Ullah Khan Alvie
#Section:23
#Student Id :22101371

input_file = open("input2b.txt", "r")
output_file = open("output2b.txt", "w")

t1 = input_file.readline().strip()
arr1 = input_file.readline().strip().split(' ')

t2 = input_file.readline().strip()
arr2 = input_file.readline().strip().split(' ')

x = 0
y = 0
new_arr=[]

while x<len(arr1) and y<len(arr2):
        if int(arr1[x]) < int(arr2[y]):
            new_arr.append(int(arr1[x]))
            x+=1
        else:
             new_arr.append(int(arr2[y]))
             y+=1

while x<len(arr1):
    new_arr.append(int(arr1[x]))
    x+=1
while y<len(arr2):
    new_arr.append(int(arr2[y]))
    y+=1
output_file.write(" ".join(map(str,new_arr)))

input_file.close()
output_file.close()