# -*- coding: utf-8 -*-
"""Task4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tnxjM-oS2vVlcn7HmvWO2Z1i5QaOYQkW
"""

#Name: Md Hasib Ullah Khan Alvie
#Section : 23
#Student Id : 22101371

input_file = open("input4.txt", "r")
output_file = open("output4.txt", "w")

test = input_file.readline().split()
test_case = int(test[0])
person = int(test[1])

lst = []

for i in range(test_case):
    lst.append(input_file.readline().split())
for i in lst:
    for j in range(len(i)):
        i[j] = int(i[j])

start_lst = []
sorted_lst = []

for i in lst:
    if i not in sorted_lst:
        start_lst.append(i[0])
start_lst.sort()

for i in start_lst:
    for j in lst:
        if i == j[0] and j not  in sorted_lst:
            sorted_lst.append(j)

result = []

def find_max (arr,n):
    if n <= 0 :
        return 0
    for i in arr:
        for j in arr:
            if i[1] <= j[0]:
                result.append(i)
                result.append(j)
                i = j
            elif len(arr) <= 1 :
                result.append(arr[0])
        temp = []

        for k in arr:
            if k not in result:
                temp.append(k)

        if arr == temp and len(result) != 0:
            result.append(arr[0])
        if len(result) != 0:
            find_max(temp,n-1)
            break

find_max(sorted_lst,person)

final_result = []
for i in result:
    if i not in final_result:
        final_result.append(i)

output_file.write(f"{len(final_result)}")


input_file.close()
output_file.close()