# -*- coding: utf-8 -*-
"""Task3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n-5-GG0_RKw8wKOC1WHkgug_QAPejNjM
"""

#Name: Md Hasib Ullah Khan Alvie
#Section:23
#Student Id :22101371

input_file = open('input3.txt', 'r')
output_file= open('output3.txt', 'w')
test = int(input_file.readline().strip())

f_lis = []
for i in range(test):
    f_lis.append(input_file.readline().strip().split())

end_list = []
for i in f_lis:
    if int(i[1]) not in end_list:
        end_list.append(int(i[1]))
end_list.sort()

sorted_list = []
sorted_list2 = []
for j in end_list:
    for k in f_lis:
        if str(j) in k[1]:
            sorted_list.append(k)
            sorted_list2.append(k)
interval = []
for i in sorted_list:
    interval.append(abs(int(i[0])-int(i[1])))
interval.sort()

min_interval = abs(int(sorted_list[0][0])- int(sorted_list[0][1]))
max_interval = interval[-1]
pre_result = [sorted_list[0]]
cnt = 0
for i in sorted_list:
    for j in sorted_list2:
        if int(i[1]) <= int(j[0]) and abs(int(i[0]) - int(i[1])) <= min_interval:
            i = j
            pre_result.append(j)
            min_interval = abs(int(j[0]) - int(j[1]))
            sorted_list.remove(j)
        else:
            sorted_list.remove(j)

    if min_interval <= max_interval:
        min_interval+=1
result = []
for i in pre_result:
    if i not in result:
        result.append(i)
        cnt+=1
output_file.write(str(cnt))
output_file.write("\n")

for i in pre_result:
    for j in i:
        output_file.write(j+' ')
    output_file.write("\n")

input_file.close()
output_file.close()