# -*- coding: utf-8 -*-
"""Untitled70.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mVueXejccVp5KG5EOxlVkM6rYHotLaP8
"""

#Name: Md Hasib Ullah Khan Alvie
#Student id: 22101371
#Section : 23

path = "/content/input3.txt"
file_3 = open(path,"r")
input = file_3.readlines()
id = input[1].split()
marks = input[2].split()

for i in range(len(id)):
    id[i], marks[i] = int(id[i]), int(marks[i])

def bubbleSort(marks, ids):
    for i in range(len(marks)-1):
        flag = False
        for j in range(len(marks)-i-1):
            if marks[j] < marks[j+1]:
                marks[j], marks[j+1] = marks[j+1], marks[j]
                ids[j], ids[j+1] = ids[j+1], ids[j]
                flag = True
            elif marks[j] == marks[j+1] and ids[j] > ids[j+1]:
                ids[j], ids[j+1] = ids[j+1], ids[j]
                flag = True
        if not flag:
            break
sorted_list = bubbleSort(marks,id)

pre_out = ""
for i in range(len(id)):
    pre_out += f'ID: {id[i]} Mark: {marks[i]}\n'

path_2 = "/content/output3.txt"
#output = open(path_2, "x")

output = open(path_2, "w")
output.writelines(pre_out)
output.close()