# -*- coding: utf-8 -*-
"""Untitled67.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g50-QfHsnWYWkatMiaiua5lgf128livy
"""

path = "/content/input1a.txt"
file_1 = open(path,"r")
temp = file_1.readlines()

for i in range(len(temp)):
    temp[i] = (temp[i].strip('\n'))
temp_2 = ["N"]
for i in temp[1:]:
    if int(i)%2== 0:
        temp_2.append("Even")
    else:
        temp_2.append("Odd")
output = ""
for i in range(1,len(temp)):
    output += f"{int(temp[i])} is an {temp_2[i]} Number.\n"

#file_2 = open("/content/output1.txt","x")

file_2 = open("/content/output1.txt","w")
file_2.writelines(output)
file_2.close()