# -*- coding: utf-8 -*-
"""Untitled71.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sR4NYJoV4Kno2Nv-mp5DOLAzrMmf1yHD
"""

#Name: Md Hasib Ullah Khan Alvie
#Student id: 22101371
#Section : 23
path = "/content/input4.txt"
file_4 = open(path, "r")
input = file_4.readlines()
n = int(input[0])
input = input[1:]

name,location,time = [],[],[]
for i in range(len(input)):
    splitted = input[i].split()
    a,b,c,d,e,f,g = tuple(splitted)
    name.append(a)
    location.append(e)
    time.append(g)

lex_time = []
for i in range(n):
    total = 0
    splitted = time[i].split(":")
    x,y = splitted
    total = int(x)*100 + int(y)
    lex_time.append(total)

for i in range(n):
    for j in range(0, n-i-1):
        if name[j] > name[j+1]:
            name[j], name[j+1] = name[j+1], name[j]
            location[j], location[j+1] = location[j+1], location[j]
            time[j], time[j+1] = time[j+1], time[j]
            lex_time[j], lex_time[j+1] = lex_time[j+1], lex_time[j]
        elif name[j] == name[j+1]:
            if lex_time[j] < lex_time[j+1]:
                location[j], location[j+1] = location[j+1], location[j]
                time[j], time[j+1] = time[j+1], time[j]
                lex_time[j], lex_time[j+1] = lex_time[j+1], lex_time[j]

output = ""
for i in range(n):
    output += f'{name[i]} will departure for {location[i]} at {time[i]}\n'
print(output)
path_4 = "/content/output4.txt"
#final = open(path_4, "x")

final = open(path_4,"w")
final.writelines(output)
final.close()