# -*- coding: utf-8 -*-
"""Untitled68.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n--PpA1KbNDdc4yZZ8oQBnK58SgKRG8V
"""

#Name: Md Hasib Ullah Khan Alvie
#Student id: 22101371
#Section : 23

path = "/content/input1b.txt"
file_1 = open(path, "r")
input = file_1.readlines()

input = input[1:]

val_1, exp, val_2 = [],[],[]
for i in range(len(input)):
    splitted = input[i].split()
    c,x,y,z = tuple(splitted)
    val_1.append(int(x))
    exp.append(y)
    val_2.append(int(z))
print(val_1,exp,val_2)

results = []
def calculator(val_1,exp,val_2):
    for i in range(len(val_1)):
        if exp[i] == "+":
            total = val_1[i] + val_2[i]
        if exp[i] == "-":
            total = val_1[i] - val_2[i]
        if exp[i] == "*":
            total = val_1[i] * val_2[i]
        if exp[i] == "/":
            total = val_1[i] / val_2[i]
        results.append(total)
pre = calculator(val_1,exp,val_2)

print(results)

output = ""
for i in range(len(val_1)):
    output += f'The result of {val_1[i]} {exp[i]} {val_2[i]} is {results[i]}\n'

path = "/content/output1b.txt"
#file_2 = open(path, "x")

file_2 = open(path, "w")
file_2.writelines(output)
file_2.close()