# -*- coding: utf-8 -*-
"""Untitled69.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ezpPNwVvZQAv4bCbc1ypjfpnwOs_5Z9j
"""

#Name: Md Hasib Ullah Khan Alvie
#Student id: 22101371
#Section : 23

path = "/content/input2.txt"
file_2 = open(path, "r")
input = file_2.readlines()
input = input[1].split()

def bubbleSort(arr):
    for i in range(len(arr)-1):
        flag = False
        for j in range(len(arr)-i-1):
            if arr[j] > arr[j+1]:
                arr[j], arr[j+1] = arr[j+1], arr[j]
                flag = True
        if flag == False:
            break

arr = []
for i in input:
    arr.append(int(i))

pre_output = bubbleSort(arr)

output = ""
for i in arr:
    output += str(i) + " "
#final = open("/content/output2.txt","x")

final = open("/content/output2.txt","w")

final.writelines(output)
final.close()

final = open("/content/output2.txt","r")

final.readlines()