# -*- coding: utf-8 -*-
"""task1a.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HmuAxxU02qfmxtWT72ah8M_p7EHAEugr
"""

#Name: Md Hasib Ullah Khan Alvie
#Section : 23
#Student ID: 22101371

input_file = open('/content/input1a.txt', 'r')
output_file = open('output1a.txt', 'w')

v, e = list(map(int, input_file.readline().strip().split()))

adj_matrix = [[0 for i in range(v+1)] for j in range(v+1)]


for i in range(e):
    x, t, w =  list(map(int, input_file.readline().strip().split()))
    adj_matrix[x][t] = w

for i in range(v+1):
    for j in range(v+1):
        output_file.write(str(adj_matrix[i][j]) + " ")
    output_file.write("\n")

input_file.close()
output_file.close()