# -*- coding: utf-8 -*-
"""Untitled81.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19Km7Kow-UpSvtwtOM3iZQUBqONCiQW9n
"""

#Name: Md Hasib Ullah Khan Alvie
#Section : 23
#Student ID: 22101371

input_file = open('/content/input1b.txt', 'r')
output_file = open('output1b.txt', 'w')

v, e = list(map(int, input_file.readline().strip().split()))

adj_list = [[] for i in range(v+1)]

for i in range(e):
    x, t, w = list(map(int, input_file.readline().strip().split()))
    adj_list[x].append((t, w))

for i in range(v+1):
    print(i, ":", end= " ", file=output_file)
    for j in range(len(adj_list[i])):
        print(adj_list[i][j], end=" ", file=output_file)
    print(file=output_file)

input_file.close()
output_file.close()

