# -*- coding: utf-8 -*-
"""task3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RFSq9JL3Wdk5eTQscaIUObRBD8j1t5qC
"""

#Name: Md Hasib Ullah Khan Alvie
#Section : 23
#Student ID: 22101371

input_file = open('input3.txt', 'r')
output_file = open('output3.txt', 'w')

v, e = list(map(int, input_file.readline().strip().split()))

vis = [0 for i in range(v+1)]
adj_list = [[]for i in range(v+1)]

for i in range(e):
    x, t = list(map(int, input_file.readline().strip().split()))
    adj_list[x].append(t)
    adj_list[t].append(x)

def DFS_Traversal(adj_list, sel):
    vis[sel] = 1
    print(sel, end=" ", file=output_file)
    for adj_node in adj_list[sel]:
        if vis[adj_node] == 0:
            DFS_Traversal(adj_list, adj_node)

sel = 1
DFS_Traversal(adj_list, sel)

input_file.close()
output_file.close()