# -*- coding: utf-8 -*-
"""task6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e23CZ5yEb6K-ZNlmX-e1ILiupnteRcHn
"""

#Name: Md Hasib Ullah Khan Alvie
#Section : 23
#Student ID: 22101371

input_file = open('input6.txt', 'r')
output_file = open('output6.txt', 'w')

v, e = list(map(int, input_file.readline().strip().split()))

grid = [list(input_file.readline().strip()) for i in range(v)]

def dfs(grid, vis, r, c):
    if r < 0 or r >= len(grid) or c < 0 or c >= len(grid[0]) or vis[r][c] or grid[r][c] == '#':
        return 0

    vis[r][c] = True
    d = 0

    if grid[r][c] == 'D':
        d += 1

    d += dfs(grid, vis, r + 1, c)
    d += dfs(grid, vis, r - 1, c)
    d += dfs(grid, vis, r, c + 1)
    d += dfs(grid, vis, r, c - 1)

    return d

max_d=0
vis = [[False] * e for i in range(v)]

def maximum(a,b):
    if a>b:
        return a
    else:
        return b

for i in range(v):
    for j in range(e):
        if grid[i][j] == '.':
            d = dfs(grid, vis, i, j)
            max_d = maximum(max_d, d)

output_file.write(str(max_d))
input_file.close()
output_file.close()