# -*- coding: utf-8 -*-
"""task2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XavfsohWxhgFJeOTcScD9wwQ7HJwWtVC
"""

#Name: Md Hasib Ullah Khan Alvie
#Section : 23
#Student ID: 22101371

input_file = open('/content/input2.txt', 'r')
output_file = open('output2.txt', 'w')

v,e = list(map(int, input_file.readline().strip().split()))

visited = [0 for i in range(v+1)]

adj_list = [[]for i in range(v+1)]

for i in range(e):
    x, t = list(map(int, input_file.readline().strip().split()))
    adj_list[x].append(t)
    adj_list[t].append(x)

def BFS_Traversal(adj_list, source):
    queue = []
    queue.append(source)
    visited[source] = 1

    while queue:
        temp = queue.pop(0)
        print(temp, end=" ", file=output_file)

        for x in adj_list[temp]:
            if visited[x] == 0:
                visited[x] = 1
                queue.append(x)

source = 1
BFS_Traversal(adj_list, source)

input_file.close()
output_file.close()