# -*- coding: utf-8 -*-
"""task4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jKvYUZMDu9I1a7cSqkrLfDA3odut1Kr9
"""

#Name: Md Hasib Ullah Khan Alvie
#Section : 23
#Student ID: 22101371

input_file = open('input4.txt', 'r')
output_file = open('output4.txt', 'w')

v, e = list(map(int, input_file.readline().strip().split()))

vis = [0 for i in range(v+1)]

adj_list = [[]for i in range(v+1)]

for i in range(e):
    f, t = list(map(int, input_file.readline().strip().split()))
    adj_list[f].append(t)


def Cycle_Detect(adj_list, selected):
    vis[selected] = 1

    for adj_node in adj_list[selected]:
        if vis[adj_node] == 0:
            Got_Cycle = Cycle_Detect(adj_list, adj_node)
            if(Got_Cycle):
                return True

        elif vis[adj_node] == 1:
            return True

    vis[selected] = 2
    return False

Cycle_Exist = False

for i in range(1, v+1):
    if vis[i] == 0:
        is_Cyclic= Cycle_Detect(adj_list, i)
        if is_Cyclic:
            Cycle_Exist = True
            break

if Cycle_Exist:
    print("YES", file=output_file)
else:
    print("NO", file=output_file)

input_file.close()
output_file.close()