# -*- coding: utf-8 -*-
"""Task1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nC3Kdv2g-YON59NZZ87d1ct7dvDoqwhF
"""

#Name : Md Hasib Ullah Khan Alvie
#Section: 23
#Student ID: 22101371

path= "/content/input1.txt"
file_1 = open(path,"r")
input = file_1.readlines()
n = int(input[0])
input = input[1].split()
for i in range(int(n)):
    input[i] = int(input[i])
file_1.close()


def merge(a, b):
    result = []
    i, j = 0, 0

    while i < len(a) and j < len(b):
        if a[i] < b[j]:
            result.append(a[i])
            i += 1
        else:
            result.append(b[j])
            j += 1
    result.extend(a[i:])
    result.extend(b[j:])
    return result
def mergeSort(arr):

    if len(arr) <= 1:
        return arr
    else:
        mid = len(arr) // 2
        left_half = mergeSort(arr[:mid])
        right_half = mergeSort(arr[mid:])
        return merge(left_half, right_half)


sorted_list = mergeSort(input)
print("Sorted list:", sorted_list)
output =""
for i in sorted_list:
    output += str(i) + " "


file_2 = open ("output1a", "w")
file_2.writelines(str(output))
file_2.close()