# -*- coding: utf-8 -*-
"""Task2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YkK_ivaVLO66yNvMMnXTWkXwjSy9LH2_
"""

#Name : Md Hasib Ullah Khan Alvie
#Section: 23
#Student ID: 22101371

path  = "/content/input2.txt"
file_1 = open(path,"r")
input = file_1.readlines()
n = int(input[0])
input = input[1].split()
for i in range(int(n)):
    input[i] = int(input[i])
file_1.close()
def find_maximum(arr):

    if len(arr) == 1:
        return arr[0]

    else:
        mid = len(arr) // 2
        left_max = find_maximum(arr[:mid])
        right_max = find_maximum(arr[mid:])
        return max(left_max, right_max)

output = find_maximum(input)
file_2 = open ("output2", "w")
file_2.writelines(str(output))
file_2.close()