# -*- coding: utf-8 -*-
"""task4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iKOFRHNsdYDjiptJS16Byi-x-5BlOFz4
"""

#NAME : MD HASIB ULLAH KHAN ALVIE
#SECTION : 23
#STUDENT ID : 22101371

input_file=open("/content/input4.txt","r")
output_file=open("output4","w")
coin,money=input_file.readline().split()
coin,money=int(coin),int(money)
var=input_file.readline().split(" ")
coin_list=[]
for i in range(len(var)):
    coin_list.append(int(var[i]))
def min_coin(coin_list,amount):
    temp=[float('inf')]*(amount+1)
    temp[0]=0
    for coin in coin_list:
        for i in range(coin,amount+1):
            temp[i] = min(temp[i],temp[i-coin]+1)
    if(temp[amount]!=float('inf')):
        return temp[amount]
    else:
        return -1
print(min_coin(coin_list,money),file=output_file)
output_file.close()