# -*- coding: utf-8 -*-
"""task2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZrDgklP1c2Y6IqBkIPtfFB-D0aVw-1jA
"""

#NAME : MD HASIB ULLAH KHAN ALVIE
#SECTION : 23
#STUDENT ID : 22101371

input_file=open("/content/input2.txt","r")
output_file=open("output2.txt","w")
num_nodes,num_edges=input_file.readline().split()
num_nodes=int(num_nodes)
num_edges=int(num_edges)
list1=[]
for i in range(num_edges):
    u,v,w =input_file.readline().split()
    u,v,w = int(u),int(v),int(w)
    m=[w,(u,v)]
    list1.append(m)

sorted_list=sorted(list1)

parent=[]
for m in range(0,num_nodes+1):
    parent.append(m)

def find(parent, i):
    if parent[i] != i:
        parent[i] = find(parent, parent[i])
    return parent[i]

def KruskalMST(sorted_list):
    minimumCost = 0
    for w, (u, v) in sorted_list:
        x = find(parent, u)
        y = find(parent, v)
        if x != y:
            minimumCost+=w
            parent[x]=y
    return minimumCost

print(KruskalMST(sorted_list),file=output_file)
output_file.close()

