# -*- coding: utf-8 -*-
"""task3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EngoGPzESBqTpiMS89iOTfrNAm6-UXjO
"""

#NAME : MD HASIB ULLAH KHAN ALVIE
#SECTION : 23
#STUDENT ID : 22101371
input_file=open(r"/content/input3.txt","r")
output_file=open(r"output3","w")
number_of_stair=int(input_file.readline())
def stairs(n):
    if n <= 2:
        return n
    jump=[0]*(n+1)
    jump[0]=0
    jump[1]=1
    jump[2]=2
    for i in range(3,n+1):
        jump[i]=jump[i-1]+jump[i-2]
    return jump[n]
print(stairs(number_of_stair),file=output_file)
output_file.close()