# -*- coding: utf-8 -*-
"""task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Llziz3-TyMjP73hht0h9OSuYTeyuv5NE
"""

#Name: Md Hasib Ullah Khan Alvie
#Section: 23
#Student ID: 22101371

with open('output1.txt', 'w') as out_s:
  with open('input1.txt') as inp_s:
    def dijkstra(source, v, e, list1, visited, d):
      d[source] = 0
      for i in range(v):
        sNode = -1
        for j in range(1, v+1):
          if visited[j] == 1:
            continue
          if(sNode == -1 or d[sNode] > d[j]):
            sNode = j
        visited[sNode] = 1

        for adj in list1[sNode]:
          aNode, edge_value = adj
          if d[sNode] + edge_value < d[aNode]:
            d[aNode] = d[sNode] + edge_value

    v1,e = map(int, inp_s.readline().split())

    list1 = [[] for i in range(v1+1)]
    visited = [0] * (v1+1)
    dic1 = [100000000] * (v1+1)

    for i in range(e):
      u,v,w = map(int, inp_s.readline().split())
      list1[u].append((v,w))

    source = int(inp_s.readline())
    dijkstra(source, v1, e, list1, visited, dic1)

    for i in dic1[1:]:
      print(i, end = " ", file = out_s)

